name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # ou qualquer branch que você queira monitorar
  workflow_dispatch:  # permite execução manual

# Adicione esta seção de permissões
permissions:
  contents: write  # Crucial para permitir push para o branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Importante para manter as credenciais

      # Seus passos de build aqui, por exemplo:
      - name: Install dependencies
        run: npm ci
        
      - name: Build docs
        run: npm run docs  # ou qualquer comando que gere sua documentação

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs  # A pasta que contém os arquivos a serem publicados
          branch: gh-pages  # O branch onde será publicado
          clean: true  # Remove arquivos antigos